language: node_js
node_js:
  - "6"
  - "8"
  - "10"
os: linux
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install: yarn
before_script: sh -c "git log | head -12"
script: yarn run coverage
after_success:
  - coveralls < ./coverage/lcov.info
  - CODECLIMATE_REPO_TOKEN=8aa40ac423a51cd32cdaa11f5b4163950263da980b9b31c19de3d920ba14579e codeclimate-test-reporter < ./coverage/lcov.info
